%YAML 1.2
---
language: python
addons:
  apt:
    packages:
    - elinks
install:
- pip install pygments
script:
- ls -a
- ls -a ~
- ls ~/virtualenv/python2.7/bin
- ~/virtualenv/python2.7/bin/pygmentize -h
- ~/virtualenv/python2.7/bin/pygmentize -g .travis.yml # YAML file
- ~/virtualenv/python2.7/bin/pygmentize -g -f terminal .travis.yml # YAML file
- ~/virtualenv/python2.7/bin/pygmentize -g -f terminal256 .travis.yml # YAML file
- ~/virtualenv/python2.7/bin/pygmentize -g  ~/virtualenv/python2.7/bin/activate_this.py # Python file
- ~/virtualenv/python2.7/bin/pygmentize .travis.yml # YAML file
- ~/virtualenv/python2.7/bin/pygmentize -f terminal .travis.yml # YAML file
- ~/virtualenv/python2.7/bin/pygmentize -f terminal256 .travis.yml # YAML file
- ~/virtualenv/python2.7/bin/pygmentize -f html .travis.yml | elinks -force-html -dump-color-mode 4 -dump
- ~/virtualenv/python2.7/bin/pygmentize -l YAML -f html .travis.yml | elinks -force-html -dump-color-mode 4 -dump
- ~/virtualenv/python2.7/bin/pygmentize  ~/virtualenv/python2.7/bin/activate_this.py # Python file
