# Travis
---
language: python
python:
# - "2.6" # Seems too old for Pygments
- "2.7"
# - "3.2" # Seems too old for Pygments
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.6-dev" # 3.6 development branch
- "3.7-dev" # 3.7 development branch
- "nightly"
addons:
  apt:
    packages:
    - elinks # does not display colors from Pygments
before_install:
- ls --color -a
- ls --color -a ~
- ls --color ~/virtualenv
- ls --color ~/virtualenv/python2.7
- ls --color ~/virtualenv/python2.7/bin
- which pip
- which pip2
- which pip3
install:
- pip install pygments # --user is required for language: <not> python to use python 2 (python 3 seems unsupported)
before_script:
- which pygmentize
- pygmentize -h
- pygmentize -L style
script:
- echo Short list
- pygmentize -P style=vim -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=native -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=fruity -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=manni -f 256 example.yaml # YAML file
- pygmentize -P style=perldoc -f 16m example.yaml # YAML file
- pygmentize -P style=rainbow_dash -f 256 example.yaml # YAML file

- echo Comprenhensive list
- pygmentize -P linenos=1 -P bg=dark example.yaml # YAML file
- pygmentize -P linenos=1 example.yaml # YAML file
- pygmentize -P linenos=1 -f html -O full example.yaml | elinks -force-html -dump-color-mode 0 -dump
- pygmentize -P linenos=1 -f html -O full example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P linenos=1 -f html -O full example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P linenos=1 -f html -O full example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P linenos=1 -f html -O full example.yaml | elinks -force-html -dump-color-mode 4 -dump

# styles for Pygments 2.2.0
- pygmentize -P style=manni -f 256 example.yaml # YAML file
- pygmentize -P style=manni -f 16m example.yaml # YAML file
- pygmentize -P style=manni -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=manni -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=manni -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=manni -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=igor -f 256 example.yaml # YAML file
- pygmentize -P style=igor -f 16m example.yaml # YAML file
- pygmentize -P style=igor -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=igor -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=igor -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=igor -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=lovelace -f 256 example.yaml # YAML file
- pygmentize -P style=lovelace -f 16m example.yaml # YAML file
- pygmentize -P style=lovelace -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=lovelace -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=lovelace -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=lovelace -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=xcode -f 256 example.yaml # YAML file
- pygmentize -P style=xcode -f 16m example.yaml # YAML file
- pygmentize -P style=xcode -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=xcode -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=xcode -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=xcode -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=vim -f 256 example.yaml # YAML file
- pygmentize -P style=vim -f 16m example.yaml # YAML file
- pygmentize -P style=vim -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=vim -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=vim -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=vim -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=autumn -f 256 example.yaml # YAML file
- pygmentize -P style=autumn -f 16m example.yaml # YAML file
- pygmentize -P style=autumn -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=autumn -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=autumn -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=autumn -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=abap -f 256 example.yaml # YAML file
- pygmentize -P style=abap -f 16m example.yaml # YAML file
- pygmentize -P style=abap -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=abap -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=abap -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=abap -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=vs -f 256 example.yaml # YAML file
- pygmentize -P style=vs -f 16m example.yaml # YAML file
- pygmentize -P style=vs -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=vs -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=vs -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=vs -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=rrt -f 256 example.yaml # YAML file
- pygmentize -P style=rrt -f 16m example.yaml # YAML file
- pygmentize -P style=rrt -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=rrt -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=rrt -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=rrt -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=native -f 256 example.yaml # YAML file
- pygmentize -P style=native -f 16m example.yaml # YAML file
- pygmentize -P style=native -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=native -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=native -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=native -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=perldoc -f 256 example.yaml # YAML file
- pygmentize -P style=perldoc -f 16m example.yaml # YAML file
- pygmentize -P style=perldoc -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=perldoc -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=perldoc -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=perldoc -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=borland -f 256 example.yaml # YAML file
- pygmentize -P style=borland -f 16m example.yaml # YAML file
- pygmentize -P style=borland -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=borland -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=borland -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=borland -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=arduino -f 256 example.yaml # YAML file
- pygmentize -P style=arduino -f 16m example.yaml # YAML file
- pygmentize -P style=arduino -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=arduino -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=arduino -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=arduino -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=tango -f 256 example.yaml # YAML file
- pygmentize -P style=tango -f 16m example.yaml # YAML file
- pygmentize -P style=tango -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=tango -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=tango -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=tango -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=emacs -f 256 example.yaml # YAML file
- pygmentize -P style=emacs -f 16m example.yaml # YAML file
- pygmentize -P style=emacs -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=emacs -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=emacs -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=emacs -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=friendly -f 256 example.yaml # YAML file
- pygmentize -P style=friendly -f 16m example.yaml # YAML file
- pygmentize -P style=friendly -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=friendly -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=friendly -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=friendly -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=monokai -f 256 example.yaml # YAML file
- pygmentize -P style=monokai -f 16m example.yaml # YAML file
- pygmentize -P style=monokai -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=monokai -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=monokai -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=monokai -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=paraiso-dark -f 256 example.yaml # YAML file
- pygmentize -P style=paraiso-dark -f 16m example.yaml # YAML file
- pygmentize -P style=paraiso-dark -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=paraiso-dark -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=paraiso-dark -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=paraiso-dark -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=colorful -f 256 example.yaml # YAML file
- pygmentize -P style=colorful -f 16m example.yaml # YAML file
- pygmentize -P style=colorful -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=colorful -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=colorful -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=colorful -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=murphy -f 256 example.yaml # YAML file
- pygmentize -P style=murphy -f 16m example.yaml # YAML file
- pygmentize -P style=murphy -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=murphy -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=murphy -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=murphy -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=bw -f 256 example.yaml # YAML file
- pygmentize -P style=bw -f 16m example.yaml # YAML file
- pygmentize -P style=bw -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=bw -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=bw -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=bw -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=pastie -f 256 example.yaml # YAML file
- pygmentize -P style=pastie -f 16m example.yaml # YAML file
- pygmentize -P style=pastie -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=pastie -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=pastie -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=pastie -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=rainbow_dash -f 256 example.yaml # YAML file
- pygmentize -P style=rainbow_dash -f 16m example.yaml # YAML file
- pygmentize -P style=rainbow_dash -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=rainbow_dash -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=rainbow_dash -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=rainbow_dash -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=algol_nu -f 256 example.yaml # YAML file
- pygmentize -P style=algol_nu -f 16m example.yaml # YAML file
- pygmentize -P style=algol_nu -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=algol_nu -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=algol_nu -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=algol_nu -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=paraiso-light -f 256 example.yaml # YAML file
- pygmentize -P style=paraiso-light -f 16m example.yaml # YAML file
- pygmentize -P style=paraiso-light -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=paraiso-light -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=paraiso-light -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=paraiso-light -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=trac -f 256 example.yaml # YAML file
- pygmentize -P style=trac -f 16m example.yaml # YAML file
- pygmentize -P style=trac -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=trac -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=trac -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=trac -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=default -f 256 example.yaml # YAML file
- pygmentize -P style=default -f 16m example.yaml # YAML file
- pygmentize -P style=default -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=default -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=default -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=default -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=algol -f 256 example.yaml # YAML file
- pygmentize -P style=algol -f 16m example.yaml # YAML file
- pygmentize -P style=algol -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=algol -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=algol -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=algol -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -P style=fruity -f 256 example.yaml # YAML file
- pygmentize -P style=fruity -f 16m example.yaml # YAML file
- pygmentize -P style=fruity -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=fruity -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P style=fruity -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P style=fruity -f html -O full -P linenos=1 example.yaml | elinks -force-html -dump-color-mode 4 -dump

# Python file
- pygmentize -P linenos=1 ~/virtualenv/python2.7/bin/activate_this.py
- pygmentize -P linenos=1 -f html -O full -P style=vim ~/virtualenv/python2.7/bin/activate_this.py | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P linenos=1 -f html -O full -P style=vim ~/virtualenv/python2.7/bin/activate_this.py | w3m -T text/html -dump # No color with w3m!

# HTML file
- pygmentize -f html -O full ~/virtualenv/python2.7/bin/activate_this.py | pygmentize -l html -P linenos=1 -f html -O full -P style=vim | elinks -force-html -dump -dump-color-mode 1
- pygmentize -f html -O full ~/virtualenv/python2.7/bin/activate_this.py
